export const PERSON_FIELDS = 'names,photos,emailAddresses';

export const CONTACT_SOURCES = [
  'READ_SOURCE_TYPE_CONTACT',
  'READ_SOURCE_TYPE_PROFILE',
  'READ_SOURCE_TYPE_DOMAIN_CONTACT',
];

export const DIR_SOURCES = [
  'DIRECTORY_SOURCE_TYPE_DOMAIN_PROFILE',
  'DIRECTORY_SOURCE_TYPE_DOMAIN_CONTACT',
];
